/**
 * Rasterizes official logo shapes from Simple Icons (CC0) into 16×16 pixel
 * grids for the retro tool logos. Output: src/data/pixelLogos.simple.ts.
 * Hand-drawn logos and any touch-ups live in src/data/pixelLogos.ts.
 *
 * simple-icons is deliberately not a project dependency. To regenerate:
 *
 *   npm i --no-save simple-icons@16
 *   npx tsx scripts/gen-pixel-logos.ts
 *
 * (Or point SIMPLE_ICONS at an installed copy: SIMPLE_ICONS=/path/to/node_modules/simple-icons.)
 * Needs Playwright's Chromium; set PLAYWRIGHT and CHROMIUM if yours live elsewhere.
 *
 * Each icon's 24×24 path is drawn 16× oversized into the 14×14 interior of
 * the tile (the outer ring is the tile's outline), then every cell is lit if
 * enough of it is covered.
 */
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";

/** tool id → Simple Icons slug. Claude Code shares Claude's mark before we add its prompt. */
const ICONS: Record<string, string> = {
  claude: "claude",
  gemini: "googlegemini",
  perplexity: "perplexity",
  notebooklm: "notebooklm",
  "github-copilot": "githubcopilot",
  cursor: "cursor",
  elevenlabs: "elevenlabs",
  zapier: "zapier",
  n8n: "n8n",
  "semantic-scholar": "semanticscholar",
  grammarly: "grammarly",
  replit: "replit",
};

/** Coverage needed to light a cell. Thin strokes get a lower bar so they don't vanish. */
const THRESHOLD: Record<string, number> = { default: 0.42, cursor: 0.4, zapier: 0.38, n8n: 0.34, githubcopilot: 0.36, notebooklm: 0.4 };

const INNER = 14;
const SUPER = 16;

async function main() {
  const require = createRequire(import.meta.url);
  const siPath = process.env.SIMPLE_ICONS ?? require.resolve("simple-icons");
  const si = (await import(pathToFileURL(siPath.endsWith(".js") || siPath.endsWith(".mjs") ? siPath : require.resolve(siPath)).href)) as Record<
    string,
    { slug: string; hex: string; path: string; title: string }
  >;
  const bySlug = new Map(Object.values(si).filter((x) => x && typeof x === "object" && "slug" in x).map((x) => [x.slug, x]));

  const pw = await import(process.env.PLAYWRIGHT ?? "/opt/node22/lib/node_modules/playwright/index.mjs");
  const browser = await pw.chromium.launch({ executablePath: process.env.CHROMIUM ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
  const page = await browser.newPage();

  const out: Record<string, { title: string; hex: string; grid: string[] }> = {};
  for (const [tool, slug] of Object.entries(ICONS)) {
    const icon = bySlug.get(slug);
    if (!icon) throw new Error(`simple-icons has no "${slug}"`);
    const cover: number[][] = await page.evaluate(
      ({ d, inner, sup }: { d: string; inner: number; sup: number }) => {
        const size = inner * sup;
        const c = document.createElement("canvas");
        c.width = c.height = size;
        const ctx = c.getContext("2d")!;
        ctx.scale(size / 24, size / 24);
        ctx.fill(new Path2D(d));
        const px = ctx.getImageData(0, 0, size, size).data;
        const rows: number[][] = [];
        for (let y = 0; y < inner; y++) {
          const row: number[] = [];
          for (let x = 0; x < inner; x++) {
            let a = 0;
            for (let sy = 0; sy < sup; sy++) for (let sx = 0; sx < sup; sx++) a += px[((y * sup + sy) * size + x * sup + sx) * 4 + 3];
            row.push(a / (255 * sup * sup));
          }
          rows.push(row);
        }
        return rows;
      },
      { d: icon.path, inner: INNER, sup: SUPER },
    );
    const t = THRESHOLD[slug] ?? THRESHOLD.default;
    const grid = [".".repeat(16)];
    for (const row of cover) grid.push("." + row.map((v) => (v >= t ? "a" : ".")).join("") + ".");
    grid.push(".".repeat(16));
    out[tool] = { title: icon.title, hex: `#${icon.hex}`, grid };
  }
  await browser.close();

  const body = Object.entries(out)
    .map(([id, v]) => `  ${JSON.stringify(id)}: {\n    // ${v.title}, brand color ${v.hex}\n    grid: [\n${v.grid.map((r) => `      "${r}",`).join("\n")}\n    ],\n  },`)
    .join("\n");
  writeFileSync(
    new URL("../src/data/pixelLogos.simple.ts", import.meta.url),
    `/* AUTO-GENERATED by scripts/gen-pixel-logos.ts from Simple Icons (CC0). Do not edit; touch up in pixelLogos.ts. */\n\nexport const SIMPLE_GRIDS: Record<string, { grid: string[] }> = {\n${body}\n};\n`,
  );
  console.log(`Wrote ${Object.keys(out).length} logos to src/data/pixelLogos.simple.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
