/**
 * Generates Material 3 color tokens (light, dark, and high-contrast variants)
 * from the USC brand colors using Google's material-color-utilities.
 *
 *   npm run theme
 *
 * Output: src/styles/tokens.css — never edit that file by hand.
 */
import { writeFileSync } from "node:fs";
import {
  argbFromHex,
  hexFromArgb,
  Hct,
  Blend,
  DynamicScheme,
  Variant,
  MaterialDynamicColors,
  TonalPalette,
} from "@material/material-color-utilities";

const CARDINAL = "#990000";
const GOLD = "#FFCC00";

/** Difficulty palette: hue families picked for meaning, then harmonized to cardinal. */
const CUSTOM = {
  beginner: "#1B8A5A",
  intermediate: GOLD,
  advanced: "#5B3FD1",
};

const ROLES = [
  "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
  "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
  "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
  "error", "onError", "errorContainer", "onErrorContainer",
  "surface", "onSurface", "surfaceVariant", "onSurfaceVariant",
  "surfaceDim", "surfaceBright",
  "surfaceContainerLowest", "surfaceContainerLow", "surfaceContainer",
  "surfaceContainerHigh", "surfaceContainerHighest",
  "inverseSurface", "inverseOnSurface", "inversePrimary",
  "outline", "outlineVariant", "shadow", "scrim",
  "primaryFixed", "primaryFixedDim", "onPrimaryFixed", "onPrimaryFixedVariant",
  "tertiaryFixed", "tertiaryFixedDim", "onTertiaryFixed", "onTertiaryFixedVariant",
] as const;

const kebab = (s: string) => s.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase());

function schemeVars(scheme: DynamicScheme): string[] {
  const out: string[] = [];
  for (const role of ROLES) {
    const color = (MaterialDynamicColors as unknown as Record<string, { getArgb(s: DynamicScheme): number }>)[role];
    out.push(`--md-sys-color-${kebab(role)}: ${hexFromArgb(color.getArgb(scheme))};`);
  }
  return out;
}

function customVars(isDark: boolean): string[] {
  const out: string[] = [];
  const source = argbFromHex(CARDINAL);
  for (const [name, hex] of Object.entries(CUSTOM)) {
    const harmonized = Blend.harmonize(argbFromHex(hex), source);
    const hct = Hct.fromInt(harmonized);
    const palette = TonalPalette.fromHueAndChroma(hct.hue, Math.max(hct.chroma, 48));
    const tones = isDark
      ? { color: 80, on: 20, container: 30, onContainer: 90 }
      : { color: 40, on: 100, container: 90, onContainer: 10 };
    out.push(`--kh-${name}: ${hexFromArgb(palette.tone(tones.color))};`);
    out.push(`--kh-on-${name}: ${hexFromArgb(palette.tone(tones.on))};`);
    out.push(`--kh-${name}-container: ${hexFromArgb(palette.tone(tones.container))};`);
    out.push(`--kh-on-${name}-container: ${hexFromArgb(palette.tone(tones.onContainer))};`);
  }
  return out;
}

/**
 * Fidelity keeps cardinal true in primaryContainer. Three deliberate overrides:
 * secondary is a quiet cardinal-tinted neutral for selection states,
 * tertiary is USC gold (the default would be a computed blue complement), and
 * neutrals are pulled down to a whisper of cardinal so surfaces read as paper,
 * not pink.
 */
function block(isDark: boolean, contrast: number): string[] {
  const source = Hct.fromInt(argbFromHex(CARDINAL));
  const gold = Hct.fromInt(argbFromHex(GOLD));
  const scheme = new DynamicScheme({
    sourceColorHct: source,
    variant: Variant.FIDELITY,
    contrastLevel: contrast,
    isDark,
    specVersion: "2025",
    secondaryPalette: TonalPalette.fromHueAndChroma(source.hue, 14),
    tertiaryPalette: TonalPalette.fromHueAndChroma(gold.hue, gold.chroma),
    neutralPalette: TonalPalette.fromHueAndChroma(source.hue, 3),
    neutralVariantPalette: TonalPalette.fromHueAndChroma(source.hue, 7),
  });
  return [...schemeVars(scheme), ...customVars(isDark)];
}

const indent = (lines: string[], n = 2) => lines.map((l) => " ".repeat(n) + l).join("\n");

const css = `/* AUTO-GENERATED by scripts/gen-theme.ts — do not edit. Seed: USC Cardinal ${CARDINAL}. */
:root,
:root[data-theme="light"] {
  color-scheme: light;
${indent(block(false, 0))}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${indent(block(true, 0), 4)}
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${indent(block(true, 0))}
}

@media (prefers-contrast: more) {
  :root:not([data-theme="dark"]) {
${indent(block(false, 1), 4)}
  }
}
`;

writeFileSync(new URL("../src/styles/tokens.css", import.meta.url), css);
console.log("Wrote src/styles/tokens.css");
